fix: workflow retries

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,9 +18,16 @@ jobs:
 
             -   name: Wait for container 1 to be healthy
                 run: |
+                    count=0
                     until curl -sf http://localhost:8080 > /dev/null; do
                         echo "waiting..."
                         sleep 1
+                        count=$((count +1))
+
+                        if [ $count == 10 ]; then
+                        echo "Could not start container, check deployment settings for site1"
+                        exit 1
+                        fi
                         done
             
             -   name: Checks HMTL5
@@ -44,9 +51,16 @@ jobs:
             
             -   name: Wait for container 2 to be healthy
                 run: |
+                    count=0
                     until curl -sf http://localhost:8081 > /dev/null; do
                         echo "waiting..."
                         sleep 1
+                        count=$((count +1))
+
+                        if [ $count == 10 ]; then
+                        echo "Could not start container, check deployment settings on site 2"
+                        exit 1
+                        fi
                         done
 
             -   name: Checks HTML5
